using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Devin.Editor.Unity
{
    /// <summary>
    /// Generates .devin/ context files so Devin IDE can understand the Unity project.
    /// </summary>
    internal static class DevinProjectContext
    {
        [InitializeOnLoadMethod]
        private static void InitializeOnLoad()
        {
            EditorApplication.delayCall += OnDelayCall;
        }

        private static void OnDelayCall()
        {
            if (DevinPreferences.AutoGenerateRules || DevinPreferences.AutoGenerateContext)
                GenerateAll();
        }

        public static void GenerateAll()
        {
            var projectRoot = UnityProjectUtility.GetProjectRoot();
            var devinDir = Path.Combine(projectRoot, ".devin");

            Directory.CreateDirectory(devinDir);

            if (DevinPreferences.AutoGenerateRules)
                GenerateRulesFile(devinDir);

            if (DevinPreferences.AutoGenerateContext)
                GenerateContextFile(devinDir);

            AssetDatabase.Refresh();
            UnityEngine.Debug.Log($"[Devin] Generated project context in {devinDir}");
        }

        private static void GenerateRulesFile(string devinDir)
        {
            var path = Path.Combine(devinDir, "rules.md");
            var content = new StringBuilder();

            content.AppendLine("# Unity Project Rules");
            content.AppendLine();
            content.AppendLine("These rules help the Devin IDE understand and work with this Unity project.");
            content.AppendLine();
            content.AppendLine("## Project Conventions");
            content.AppendLine();
            content.AppendLine("- This is a Unity project. C# scripts are the primary source files under `Assets/`.");
            content.AppendLine("- Scene files (`.unity`) and prefabs (`.prefab`) are YAML-based Unity assets. Treat them as data, not code.");
            content.AppendLine("- The `Library/`, `Temp/`, `Logs/`, `obj/`, and `Build/` folders are generated and should be ignored.");
            content.AppendLine("- Meta files (`.meta`) store Unity GUIDs and import settings. Do not delete them manually.");
            content.AppendLine();
            content.AppendLine("## When Editing Scripts");
            content.AppendLine();
            content.AppendLine("- Prefer using `UnityEngine` APIs and follow Unity C# conventions.");
            content.AppendLine("- Avoid blocking the main thread with long-running operations in `Update`.");
            content.AppendLine("- Use `SerializedObject` / `SerializedProperty` when writing Editor tools.");
            content.AppendLine("- Keep gameplay logic in `MonoBehaviour` systems and avoid tight coupling to Unity Editor APIs at runtime.");
            content.AppendLine();
            content.AppendLine("## Naming");
            content.AppendLine();
            content.AppendLine("- Use PascalCase for public classes, methods, and properties.");
            content.AppendLine("- Use camelCase for private fields and local variables.");
            content.AppendLine("- Prefix Unity Editor-only types with the project namespace when possible.");
            content.AppendLine();
            content.AppendLine("## Generated Folders");
            content.AppendLine();
            content.AppendLine("- `.devin/` is generated by the Devin Editor for Unity package and is safe to commit.");

            File.WriteAllText(path, content.ToString(), Encoding.UTF8);
        }

        private static void GenerateContextFile(string devinDir)
        {
            var path = Path.Combine(devinDir, "context.md");
            var content = new StringBuilder();

            content.AppendLine("# Unity Project Context");
            content.AppendLine();
            content.AppendLine($"- **Project Name**: {Application.productName}");
            content.AppendLine($"- **Unity Version**: {Application.unityVersion}");
            content.AppendLine($"- **Platform**: {Application.platform}");
            content.AppendLine($"- **Product GUID**: {PlayerSettings.productGUID}");
            content.AppendLine($"- **Scripting Backend**: {PlayerSettings.GetScriptingBackend(BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget))}");
            content.AppendLine($"- **Api Compatibility Level**: {PlayerSettings.GetApiCompatibilityLevel(BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget))}");
            content.AppendLine();

            AppendPackages(content);
            AppendAssemblies(content);
            AppendScriptSummary(content);
            AppendSceneSummary(content);

            File.WriteAllText(path, content.ToString(), Encoding.UTF8);
        }

        private static void AppendPackages(StringBuilder content)
        {
            content.AppendLine("## Packages");
            content.AppendLine();
            var packages = UnityEditor.PackageManager.PackageInfo.GetAllRegisteredPackages()
                .OrderBy(p => p.name)
                .ToArray();

            if (packages.Length == 0)
            {
                content.AppendLine("No packages found.");
            }
            else
            {
                foreach (var package in packages)
                {
                    if (!DevinPreferences.IncludeExternalPackages && package.source == UnityEditor.PackageManager.PackageSource.Registry)
                        continue;

                    content.AppendLine($"- `{package.name}` @ `{package.version}` ({package.source})");
                }
            }
            content.AppendLine();
        }

        private static void AppendAssemblies(StringBuilder content)
        {
            content.AppendLine("## Assembly Definitions");
            content.AppendLine();
            var asmdefFiles = Directory.GetFiles(UnityProjectUtility.GetAssetsPath(), "*.asmdef", SearchOption.AllDirectories);
            if (asmdefFiles.Length == 0)
            {
                content.AppendLine("No custom assembly definitions found. Scripts compile into the default Assembly-CSharp assembly.");
            }
            else
            {
                foreach (var asmdef in asmdefFiles)
                {
                    content.AppendLine($"- `{UnityProjectUtility.GetRelativePath(asmdef)}`");
                }
            }
            content.AppendLine();
        }

        private static void AppendScriptSummary(StringBuilder content)
        {
            content.AppendLine("## Scripts");
            content.AppendLine();
            var scripts = Directory.GetFiles(UnityProjectUtility.GetAssetsPath(), "*.cs", SearchOption.AllDirectories)
                .Where(path => !path.Contains("/Editor/") && !path.Contains("\\Editor\\"))
                .OrderBy(path => path)
                .ToArray();

            content.AppendLine($"Total runtime C# scripts: {scripts.Length}");
            foreach (var script in scripts.Take(50))
            {
                content.AppendLine($"- `{UnityProjectUtility.GetRelativePath(script)}`");
            }
            if (scripts.Length > 50)
                content.AppendLine($"- ... and {scripts.Length - 50} more");
            content.AppendLine();
        }

        private static void AppendSceneSummary(StringBuilder content)
        {
            content.AppendLine("## Scenes");
            content.AppendLine();
            var scenes = Directory.GetFiles(UnityProjectUtility.GetAssetsPath(), "*.unity", SearchOption.AllDirectories)
                .OrderBy(path => path)
                .ToArray();

            if (scenes.Length == 0)
            {
                content.AppendLine("No scenes found.");
            }
            else
            {
                foreach (var scene in scenes)
                {
                    content.AppendLine($"- `{UnityProjectUtility.GetRelativePath(scene)}`");
                }
            }
            content.AppendLine();
        }
    }
}
